# This workflow will build and deploy a Python Flask app to Azure Web App using GitHub Actions
# Make sure to set AZURE_WEBAPP_NAME, AZURE_WEBAPP_PUBLISH_PROFILE, and PYTHON_VERSION as GitHub secrets

name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ secrets.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ secrets.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip application for deployment
        run: |
          zip -r app.zip .

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          package: app.zip
          scm-do-build-during-deployment: true
          # Use Azure credentials for authentication
          publish-profile: ''
          # The following enables deployment using Azure credentials
          # (Make sure AZURE_CREDENTIALS secret is set with service principal JSON)
